services:
  grafana:
    container_name: "ddev-${DDEV_SITENAME}-grafana"
    image: grafana/grafana:latest
    user: "${UID:-}:${GID:-}"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTPS_EXPOSE=3000:3000
